// frontend-react/src/components/ExpenseForm.tsx
import { useState, type FormEvent } from 'react'
import { api, type Split, type SplitType, type User } from '../api'
import { rupeesToPaise, today } from '../money'
import ErrorMessage from './ErrorMessage'

interface Props {
  groupId: number | null
  members?: User[]
  onCreated: () => void
}

export default function ExpenseForm({ groupId, members, onCreated }: Props) {
  const [amount, setAmount] = useState('')
  const [category, setCategory] = useState('')
  const [description, setDescription] = useState('')
  const [spentOn, setSpentOn] = useState(today())
  const [splitType, setSplitType] = useState<SplitType>('equal')
  const [shares, setShares] = useState<Record<number, string>>({})
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const isGroup = groupId !== null && members !== undefined

  function buildSplits(): Split[] | undefined {
    if (!isGroup) return undefined
    if (splitType === 'equal') return members.map((m) => ({ user_id: m.id, share_paise: 0 }))
    return members.map((m) => {
      const raw = shares[m.id] ?? ''
      const value = splitType === 'exact' ? rupeesToPaise(raw) : Math.round(Number(raw))
      return { user_id: m.id, share_paise: Number.isFinite(value) ? value : 0 }
    })
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    const amountPaise = rupeesToPaise(amount)
    if (!Number.isFinite(amountPaise) || amountPaise <= 0) {
      setError('Amount must be greater than zero')
      return
    }
    setSubmitting(true)
    setError(null)
    try {
      await api.createExpense({
        group_id: groupId,
        amount_paise: amountPaise,
        category,
        description,
        spent_on: spentOn,
        split_type: isGroup ? splitType : 'equal',
        splits: buildSplits(),
      })
      setAmount('')
      setCategory('')
      setDescription('')
      setShares({})
      onCreated()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="card">
      <h3>Add expense</h3>
      <div className="row">
        <label>
          Amount (INR)
          <input
            type="number"
            step="0.01"
            min="0.01"
            required
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
          />
        </label>
        <label>
          Category
          <input required value={category} onChange={(e) => setCategory(e.target.value)} />
        </label>
        <label>
          Date
          <input type="date" required value={spentOn} onChange={(e) => setSpentOn(e.target.value)} />
        </label>
      </div>
      <label>
        Description
        <input required value={description} onChange={(e) => setDescription(e.target.value)} />
      </label>
      {isGroup && (
        <>
          <label>
            Split
            <select value={splitType} onChange={(e) => setSplitType(e.target.value as SplitType)}>
              <option value="equal">Equal</option>
              <option value="exact">Exact amounts</option>
              <option value="percent">Percentages</option>
            </select>
          </label>
          {splitType !== 'equal' && (
            <div className="row">
              {members.map((m) => (
                <label key={m.id}>
                  {m.name} {splitType === 'exact' ? '(INR)' : '(%)'}
                  <input
                    type="number"
                    step={splitType === 'exact' ? '0.01' : '1'}
                    min="0"
                    required
                    value={shares[m.id] ?? ''}
                    onChange={(e) => setShares({ ...shares, [m.id]: e.target.value })}
                  />
                </label>
              ))}
            </div>
          )}
        </>
      )}
      <ErrorMessage message={error} />
      <button type="submit" disabled={submitting}>
        {submitting ? 'Saving...' : 'Add expense'}
      </button>
    </form>
  )
}

// frontend-angular/src/app/shared/expense-form/expense-form.ts
import { Component, inject, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, Expense, Split, SplitType, User, apiError } from '../api.service';
import { toPaise } from '../money.pipe';

@Component({
  selector: 'app-expense-form',
  imports: [FormsModule],
  templateUrl: './expense-form.html',
})
export class ExpenseForm {
  private api = inject(ApiService);
  groupId = input<number | null>(null);
  members = input<User[]>([]);
  created = output<Expense>();

  amount = '';
  category = '';
  description = '';
  spentOn = new Date().toISOString().slice(0, 10);
  splitType: SplitType = 'equal';
  excluded = new Set<number>();
  shares: Record<number, string> = {};
  busy = signal(false);
  error = signal('');

  isIncluded(userId: number) {
    return !this.excluded.has(userId);
  }

  toggle(userId: number) {
    if (this.excluded.has(userId)) {
      this.excluded.delete(userId);
    } else {
      this.excluded.add(userId);
    }
  }

  submit() {
    this.busy.set(true);
    this.error.set('');
    this.api
      .createExpense({
        group_id: this.groupId(),
        amount_paise: toPaise(this.amount),
        category: this.category,
        description: this.description,
        spent_on: this.spentOn,
        split_type: this.splitType,
        splits: this.members().length ? this.buildSplits() : undefined,
      })
      .subscribe({
        next: (expense) => {
          this.busy.set(false);
          this.amount = '';
          this.description = '';
          this.created.emit(expense);
        },
        error: (err) => {
          this.busy.set(false);
          this.error.set(apiError(err));
        },
      });
  }

  private buildSplits(): Split[] {
    const members = this.members();
    switch (this.splitType) {
      case 'equal':
        return members
          .filter((m) => this.isIncluded(m.id))
          .map((m) => ({ user_id: m.id, share_paise: 0 }));
      case 'exact':
        return members.map((m) => ({
          user_id: m.id,
          share_paise: toPaise(this.shares[m.id] || 0),
        }));
      case 'percent':
        return members.map((m) => ({ user_id: m.id, share_paise: Number(this.shares[m.id] || 0) }));
    }
  }
}
